# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\x12\nclassifier\"%\n\x15\x43lassificationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"3\n\x0e\x43lassification\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\\\n\x0fMBertClassifier\x12I\n\x08\x43lassify\x12!.classifier.ClassificationRequest\x1a\x1a.classifier.Classificationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFICATIONREQUEST']._serialized_start=32
  _globals['_CLASSIFICATIONREQUEST']._serialized_end=69
  _globals['_CLASSIFICATION']._serialized_start=71
  _globals['_CLASSIFICATION']._serialized_end=122
  _globals['_MBERTCLASSIFIER']._serialized_start=124
  _globals['_MBERTCLASSIFIER']._serialized_end=216
# @@protoc_insertion_point(module_scope)
